[package]
name = "spectral_compressor"
version = "1.1.1"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>", "ferropop"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/ferropop/spectral-compressor-turbo"
repository = "https://github.com/ferropop/spectral-compressor-turbo"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nih_plug = { path = "../../", features = ["assert_process_allocs", "standalone"] }
nih_plug_vizia = { path = "../../nih_plug_vizia" }

realfft = "3.0"

# For the GUI
atomic_float = "0.1"
crossbeam = "0.8"
open = "3.0"
serde = { version = "1.0", features = ["derive"] }
triple_buffer = "6.2"
serde_json = "1.0"
